apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rickjames
spec:
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: rickjames
        app: rickjames
    spec:
      containers:
      - name: rickjames
        image: vallard/rickjames:{{ build.number }}
        env:
        - name: SPARK_TOKEN
          valueFrom:
            secretKeyRef:
              name: rickjames-secrets
              key: SPARK_TOKEN
        - name: KEYWORD
          value: "hello"
        - name: RESPONSE
          value: "Hello back to you my friend!"
        ports:
        - containerPort: 8080
