apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bot.rickjames
spec:
  rules:
    - host: bots.ciscopipeline.io
      http:
        paths:
          - backend:
              serviceName: rickjames
              servicePort: 8080
            path: /vallard/rickjames
